encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("createentry", views.createEntry, name="createentry"),
    path("editentry/<str:title>", views.editEntry, name="editentry"),
    path("randomentry", views.randomEntry, name="randomentry"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from . import util
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse
import random
import markdown2

class SearchForm(forms.Form):
    searchEntry = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))

class CreateEntryForm(forms.Form):
    entryTitle = forms.CharField(label="Title:", widget=forms.TextInput(attrs={'placeholder': "Title"}))
    markdownContent = forms.CharField(label="Markdown Content:", widget=forms.Textarea(attrs={'placeholder': "Markdown content for this page...",'style': 'height: 200px;width:500px'}))

class EditEntryForm(forms.Form):
    markdownContent = forms.CharField(label="", required=False, widget=forms.Textarea(attrs={'style': 'height: 200px;width:500px'}))

def index(request):                                  
    if request.method == "POST":
        searchForm = SearchForm(request.POST)
        if searchForm.is_valid():
            searchResults = []
            searchEntry = searchForm.cleaned_data["searchEntry"]
            entries = util.list_entries()
            for entry in entries:
                if len(searchEntry)!=len(entry) and searchEntry.lower() in entry.lower():
                    searchResults.append(entry)
            
            if searchResults:
                return render(request, "encyclopedia/index.html", {
                    "entries": searchResults,
                    "searchForm": searchForm,
                    "related_entries": True
                }) 
            
            for entry in entries:
                if len(searchEntry)==len(entry) and searchEntry.lower() in entry.lower():
                    resultMatched = True
                    if resultMatched:
                        return render(request, "encyclopedia/entry.html", {
                            "entries": searchEntry,
                            "searchForm": searchForm,
                            "title" : util.get_entry(searchEntry),
                            "title": entry,
                            "markdown" : markdown2.markdown(util.get_entry(entry))
                        })
            

            for entry in entries:
                if len(searchEntry)!=len(entry) and searchEntry.lower() not in entry.lower():
                    return render(request, "encyclopedia/error.html", {
                        "searchForm" : SearchForm(),
                        "errorMessage" : 'No entry is available of your searched name!'
                    })
                    
            

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "searchForm" : SearchForm()
    })

def entry(request, title):
    if title in util.list_entries():
        return render(request, "encyclopedia/entry.html", {
            "searchForm" : SearchForm(),
            "title": title,
            "markdown" : markdown2.markdown(util.get_entry(title))
        })
    else:
        return render(request, "encyclopedia/error.html", {
            "searchForm" : SearchForm(),
            "errorMessage" : 'Sorry your requested page was not found. No entry is available by this name!'
        })
    

def createEntry(request):
    if request.method == "POST":
        createEntryform = CreateEntryForm(request.POST)
        if createEntryform.is_valid():
            entryTitle = createEntryform.cleaned_data["entryTitle"]
            markdownContent = createEntryform.cleaned_data["markdownContent"]
            entries = util.list_entries()
            for entry in entries:
                if entryTitle.lower() == entry.lower():
                    return render(request, "encyclopedia/error.html", {
                        "searchForm" : SearchForm(),
                        "errorMessage" : "ERROR:: Sorry!!! An entry with this title is already available in the entries, so try with another title!"
                    })
                    
                    
            return render(request, 'encyclopedia/entry.html', {
                "searchForm" : SearchForm(),
                "title": entryTitle,
                "markdownContent": markdownContent,
                "save_entry" : util.save_entry(entryTitle, markdownContent)
            })

    return render(request, "encyclopedia/createEntry.html", {
        "searchForm" : SearchForm(),
        "createEntryform": CreateEntryForm()
    })

def editEntry(request, title):
    if request.method == "POST":
        editEntryForm = EditEntryForm(request.POST)
        if editEntryForm.is_valid():
            markdownContent = editEntryForm.cleaned_data["markdownContent"]
            return render(request, 'encyclopedia/entry.html', {
                    "searchForm" : SearchForm(),
                    "title": title,
                    "markdown": markdown2.markdown(markdownContent),
                    "save_entry" : util.save_entry(title, markdownContent)
                })
        else:
            return render(request, "encyclopedia/error.html", {
                    "searchForm" : SearchForm(),
                    "errorMessage" : 'ERROR:: Sorry! Updating failed..'
                })
    
    editEntryForm = EditEntryForm(request.GET, initial={'markdownContent': markdown2.markdown(util.get_entry(title))})
    return render(request, "encyclopedia/editEntry.html", {
        "searchForm" : SearchForm(),
        'editEntryForm' : editEntryForm,
        "title": title,
        "markdownContent": util.get_entry(title)
    })

def randomEntry(request):
    entries = util.list_entries()
    randomEntry = random.choice (entries)
    return render(request, 'encyclopedia/entry.html', {
        "searchForm" : SearchForm(),
        "title": randomEntry,
        "markdown" : markdown2.markdown(util.get_entry(randomEntry))
    })

encyclopedia/templates/encyclopedia/createEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create a new Entry</h1>
    <form action="{% url 'encyclopedia:createentry' %}" method="POST">
        {% csrf_token %}
        <div>
            {{ createEntryform.entryTitle }}
        </div>
        <div>
            {{ createEntryform.markdownContent }}
        </div>
        <input type="submit"/>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/editEntry.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
<h1>Edit the Markdown content of {{ title }}</h1>
<form action="{% url 'encyclopedia:editentry' title %}" method="POST">
    {% csrf_token %}
    {{ editEntryForm }}
    <br>
    <small>Here is the prepopulated value. You can copy it to your textarea field for editting in case!</small>
    <br>
    <small> <strong>Old Content: </strong> <em>{{ markdownContent }}</em></small>
    <br>
    <!-- <textarea name="markdown" style="height: 200px; width: 500px">{{ markdownContent }}</textarea> -->
    <input type="submit" value="Update" />
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1> {{ title }} </h1>
    <h2>{{ markdown }}</h2>
    <a href="{% url 'encyclopedia:editentry' title %}">Edit Markdown Content</a>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %} {% block title %} Encyclopedia {% endblock %} {% block body %}

<div class="alert alert-danger" role="alert">
    {{ errorMessage }}
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
{% if related_entries %}
<h1>Did you mean?</h1>
{% elif errorMessage %}
<div class="alert alert-danger" role="alert">
    {{ errorMessage }}
</div>
{% else %}
<h1>All Pages</h1>
{% endif %}

<ul>
    {% if entries %}
    {% for entry in entries %}
    <a href="{% url 'encyclopedia:entry' entry %}">
        <li>{{ entry }}</li>
    </a>
    {% endfor %}
    {% endif %}
</ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="POST">
                    {% csrf_token %}
                    {{ searchForm }}
                    <input type="submit" placeholder="Search" value="Search"/>
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:createentry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randomentry' %}">Random Page</a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>